language: python

python:
  - 2.6
  - 2.7

before_install:
  - pip install --use-mirrors PyYAML SQLAlchemy 'Tornado<2.0'

install:
  - python setup.py install

script: bin/testify --exclude catbox test
